name: Deploy MINFIN Linux Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip nginx
        
    - name: Validate HTML files
      run: |
        find plataforma -name "*.html" -exec echo "Validating {}" \;
        # Add HTML validation here if needed
        
    - name: Test platform structure
      run: |
        echo "Testing platform structure..."
        ls -la plataforma/
        ls -la plataforma/modulos/
        echo "✅ Platform structure validated"
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to MINFIN server..."
        # Add deployment commands here
        # This would typically involve:
        # 1. SSH to server
        # 2. Pull latest changes
        # 3. Restart services
        # 4. Verify deployment
        
    - name: Notify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Platform available at: http://your-server:8000"
